# which base image?
FROM nginx:1.25 

# set a working directory inside the image
WORKDIR /usr/share/nginx/html/

# copy all the files to that working dir
COPY index.html .

# define the port number the container should expose
EXPOSE 80
